### ISSUE TITLE
Pretty sure send_fields was deprecated

### ISSUE THREAD

**Issue by mike-bailey** [slack-ruby/slack-aws#1]
Getting a NoMethodError on send_fields and send_message was deprecated so send_fields was probably deprecated and maybe so was send_message_with_gif.

**Comment by dblock** [comment]
Haven't touched this project in a long time, feel free to upgrade it.

**Comment by mike-bailey** [comment]
I notice you do slack-ruby-bot and the like as well. Can you verify that send_fields is deprecated?

**Comment by mike-bailey** [comment]
If so, I can use client.say.

**Comment by dblock** [comment]
In 0.6.0 `send_` was deprecated for `say`, see https://github.com/slack-ruby/slack-ruby-bot/blob/master/CHANGELOG.md.

**Comment by mike-bailey** [comment]
Doesn't look like send_fields is referenced however

**Comment by dblock** [comment]
Oh wait, `send_fields` is a method in this project, it's not something from slack-ruby-bot. See https://github.com/slack-ruby/slack-aws/blob/81c9150d87b2b0561dba7688b856ed262f1ecb50/slack-aws/util/aws_client_response.rb#L4. I'll close this.

**Comment by mike-bailey** [comment]
Can you reopen? My original purpose for opening this was to fork and patch in this project. The fact that it's in this project doesn't really change that...
